config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'tv_shows/index'
  get 'movies/index'
  get 'games/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :games, only: [:index]
  resources :movies, only: [:index]
  resources :tv_shows, only: [:index]
  resources :works, only: [:index, :new, :create, ]
  get '/search', to: 'search#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  attr_accessor :watch_date

  # scope :search_by_name, -> (name) { where("name ILIKE ?", "%#{name}%") }

  has_one_attached :image

  def self.search(term)
    where("name ALIKE ?", "%#{term}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require 'httparty'

  def index
    response = HTTParty.get('https://api.twitch.tv/helix/games/top', headers: {
      "u8mhg8u181nax39uf2k9sj5ttv7k6b" => ENV['TWITCH_CLIENT_ID']
    })
    if response.code == 200
      @games = JSON.parse(response.body)['data']
    else
      puts "Erreur lors de l'appel API"
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController


  def index
    if params[:query].present?
      sql_query = <<~SQL
       works.name @@ :query
       OR works.creator ILIKE :query
       SQL
      @works = Work.where(sql_query, query: "%#{params[:query]}%")
    else
      @works = Work.all
    end
  end

  def search
    @works = Work.search_by_name(params[:search])
    respond_to do |format|
      format.js
    end
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)

    if @work.save
      redirect_to works_path, notice: "L'oeuvre a bien été créée !"
    else
      render :new
    end
  end


  private

  def work_params
    params.require(:work).permit(:name, :year, :creator, :image, :watch_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Liste des jeux</h1>

<% if @games %>
  <% @games.each do |game| %>
    <div>
      <h2><%= game.name %></h2>
      <p>Année de production : <%= game.year %></p>
      <img src="<%= game.image %>">
    </div>
  <% end %>
<% else %>
  <p>Aucun jeu n'a été trouvé.</p>
<% end %>

<% if @error %>
  <p>Une erreur est survenue : <%= @error %></p>
<% end %>

<% puts "DEBUG: @games = #{@games.inspect}" %>
<% puts "DEBUG: @error = #{@error.inspect}" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgendaTest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

app/views/pages/home.html.erb
<h1>Home qui va bientôt afficher des films randomément mais là je bosse sur mes textes défilants sur twitch</h1>
<p>Liste des oeuvres que j'ai consommé, wouhou on y retourne</p>

<a href="/works">Liste à venir    </a>

app/views/pages/movies_template.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liste des films populaires</title>
  </head>
  <body>
    <h1>Liste des films populaires</h1>
    <ul>
      <% @movies.each do |movie| %>
        <li>
          <%= movie['title'] %>
          <img src="https://image.tmdb.org/t/p/w500<%= movie['poster_path'] %>" alt="<%= movie['title'] %>">
        </li>
      <% end %>
    </ul>
  </body>
</html>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tv_shows/index.html.erb
<h1>TvShows#index</h1>
<p>Find me in app/views/tv_shows/index.html.erb</p>

app/views/works/_works_list.html.erb
<% @works.each do |work| %>
  <div class="work">
    <%= image_tag work.image, class: "work-image" %>
    <div class="work-info">
      <h3><%= work.name %></h3>
      <p><strong>Année de sortie :</strong> <%= work.year %></p>
      <p><strong>Créateur :</strong> <%= work.creator %></p>
    </div>
  </div>
<% end %>

app/views/works/index.html.erb
<h1>Liste des œuvres connues</h1>

<div class="container">
  <div class="search-form">
  <%= form_with url: works_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a movie"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  </div>



  <div class="works">
    <% @works.each do |work| %>
      <div class="work">
        <%= image_tag work.image, class: "work-image" %>
        <div class="work-info">
          <h3><%= work.name %></h3>
          <p><strong>Année de sortie :</strong> <%= work.year %></p>
          <p><strong>Créateur :</strong> <%= work.creator %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "Ajouter une œuvre", new_work_path %>

app/views/works/new.html.erb
<%= form_with(model: @work, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :creator %>
    <%= form.text_field :creator, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :watch_date %>
    <%= form.date_field :watch_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/works/search.js.erb
$(".work-container").html("<%= j render partial: 'works_list', locals: { works: @works } %>");